version: '3.7'

services:
  backend:
    build:
      context: .\backend_api\simple-api-student-main
      dockerfile: Dockerfile
    image: backend_api
    networks:
      - my-network
    depends_on:
      - database

  database:
    build:
      context: .\database
      dockerfile: Dockerfile
    image: takima-db
    networks:
      - my-network

  httpd:
    build:
      context: .\http_server
      dockerfile: Dockerfile
    image: http_server
    ports:
      - "8080:80"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
