name: CI DevOps 2024
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and Test with Maven
        working-directory: ./backend_api/simpleapi
        run: mvn clean install

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.5.0

      - name: Verify Directory Structure
        run: |
          ls -R backend_api
          ls -R database
          ls -R http_server

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend_api ./backend_api/simpleapi
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend_api
  
      - name: Build and Push Database Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/takima-db ./database
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/takima-db
  
      - name: Build and Push HTTP Server Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/http_server ./http_server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/http_server
